// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
import "dotenv/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: { path: "prisma/migrations" },
  datasource: {
    url: process.env["FRONTEND_DATABASE_URL"] ?? process.env["DATABASE_URL"],
  },
  adapter: {
    provider: "prisma-client-js",
    driverAdapters: [
      {
        driver: "pg",
        package: "@prisma/adapter-pg",
      },
    ],
  },
});
